CREATE TABLE IF NOT EXISTS HTTP_JOBS
(
    JOB_ID          SERIAL PRIMARY KEY,
    JOB_NAME        VARCHAR(255) UNIQUE NOT NULL,
    JOB_DESCRIPTION VARCHAR(255)        NOT NULL,
    JOB_URL         VARCHAR(255),
    AUTH_TOKEN      VARCHAR(255)        NOT NULL,
    SCHEDULE_TIME   VARCHAR(255)        NOT NULL,
    CREATED_BY      VARCHAR(255)        NOT NULL,
    CREATED_AT      TIMESTAMP           NOT NULL,
    UPDATED_BY      VARCHAR(255)        NOT NULL,
    UPDATED_AT      TIMESTAMP           NOT NULL,
    IS_RUNNING      BOOLEAN DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PULSAR_JOBS
(
    JOB_ID          SERIAL PRIMARY KEY,
    JOB_NAME        VARCHAR(255) NOT NULL,
    JOB_DESCRIPTION VARCHAR(255) NOT NULL,
    TOPIC_NAME      VARCHAR(255) NOT NULL,
    TOPIC_URL       VARCHAR(255),
    SCHEDULE_TIME   VARCHAR(255) NOT NULL,
    CREATED_BY      VARCHAR(255) NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    UPDATED_BY      VARCHAR(255) NOT NULL,
    UPDATED_AT      TIMESTAMP    NOT NULL,
    IS_RUNNING      BOOLEAN DEFAULT FALSE
);
