import { ColorVariant } from '../interfaces/color-variants.interface';

export const COLOR_VARIANTS: ColorVariant[] = [
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Black',
    arabicColorName: 'Ø£Ø³ÙˆØ¯',
    color: '#000000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Dark Slate Grey',
    arabicColorName: 'Ø±Ù…Ø§Ø¯ÙŠ Ø´Ø§Ø­Ø¨ ØºØ§Ù…Ù‚',
    color: '#2f4f4f',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Grey',
    arabicColorName: 'Ø±Ù…Ø§Ø¯ÙŠ',
    color: '#808080',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Dark Gray',
    arabicColorName: 'Ø±Ù…Ø§Ø¯ÙŠ ØºØ§Ù…Ù‚',
    color: '#a9a9a9',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Light Grey',
    arabicColorName: 'Ø±Ù…Ø§Ø¯ÙŠ ÙØ§ØªØ­',
    color: '#d3d3d3',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø±Ù…Ø§Ø¯ÙŠØ©',
    colorName: 'Silver',
    arabicColorName: 'ÙØ¶ÙŠ',
    color: '#c0c0c0',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨ÙŠØ¶Ø§Ø¡',
    colorName: 'White',
    arabicColorName: 'Ø£Ø¨ÙŠØ¶',
    color: '#ffffff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨ÙŠØ¶Ø§Ø¡',
    colorName: 'Light Cyan',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ Ø³Ù…Ø§ÙˆÙŠ ÙØ§ØªØ­',
    color: '#e0ffff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨ÙŠØ¶Ø§Ø¡',
    colorName: 'Beige',
    arabicColorName: 'Ø§Ù„Ø¨ÙŠØ¬',
    color: '#f5f5dc',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Maroon',
    arabicColorName: 'Ù…Ø§Ø±ÙˆÙ†ÙŠ',
    color: '#800000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Sienna',
    arabicColorName: 'Ø³ÙŠÙŠÙ†Ø§',
    color: '#a0522d',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Brown',
    arabicColorName: 'Ø¨Ù†ÙŠ',
    color: '#8b4513',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Chocolate',
    arabicColorName: 'Ø´ÙŠÙƒÙˆÙ„Ø§ØªØ©',
    color: '#d2691e',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Sandy Brown',
    arabicColorName: 'Ø¨Ù†ÙŠ Ø±Ù…Ù„ÙŠ',
    color: '#f4a460',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Bronze',
    arabicColorName: 'Ù†Ø­Ø§Ø³ÙŠ',
    color: '#dca270',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Burly Wood',
    arabicColorName: 'Ø®Ø´Ø¨ÙŠ',
    color: '#deb887',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Kashmir',
    arabicColorName: 'ÙƒØ´Ù…ÙŠØ±',
    color: '#ccae94',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø³Ù…Ø±Ø§Ø¡ (Ø§Ù„Ø¨Ù†ÙŠ)',
    colorName: 'Creamy',
    arabicColorName: 'ÙƒØ±ÙŠÙ…ÙŠ',
    color: '#fffdd0',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Prussian Blue',
    arabicColorName: 'ÙƒØ­Ù„ÙŠ ØºØ§Ù…Ù‚',
    color: '#000033',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Navy',
    arabicColorName: 'ÙƒØ­Ù„ÙŠ',
    color: '#000066',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Darkblue',
    arabicColorName: 'Ø£Ø²Ø±Ù‚ ØºØ§Ù…Ù‚',
    color: '#00008b',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Blue',
    arabicColorName: 'Ø£Ø²Ø±Ù‚',
    color: '#0000ff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Medium Slate Blue',
    arabicColorName: 'Ø£Ø²Ø±Ù‚ Ø±Ù…Ø§Ø¯ÙŠ Ù…ØªÙˆØ³Ø·',
    color: '#7b68ee',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Dodger Blue',
    arabicColorName: 'Ø£Ø²Ø±Ù‚ Ù…Ø±Ø§ÙˆØº',
    color: '#1e90ff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Deep Sky Blue',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ Ø³Ù…Ø§ÙˆÙŠ Ø¹Ù…ÙŠÙ‚',
    color: '#00bfff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Sky Blue',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ Ø³Ù…Ø§ÙˆÙŠ',
    color: '#87ceeb',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Steel Blue',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ Ø±Ù…Ø§Ø¯ÙŠ',
    color: '#4682b4',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Cadet Blue',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ ÙƒØ§Ø¯ÙŠØª',
    color: '#5f9ea0',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Turquoise',
    arabicColorName: 'ÙÙŠØ±ÙˆØ²ÙŠ',
    color: '#40e0d0',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Pale Turquoise',
    arabicColorName: 'ØªØ±ÙƒÙˆØ§Ø² Ø´Ø§Ø­Ø¨',
    color: '#afeeee',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø²Ø±Ù‚Ø§Ø¡',
    colorName: 'Aqua',
    arabicColorName: 'Ø³Ù…Ø§ÙˆÙŠ',
    color: '#00ffff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Dark Cyan',
    arabicColorName: 'Ø³Ù…Ø§ÙˆÙŠ ØºØ§Ù…Ù‚',
    color: '#008b8b',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Dark Olive Green',
    arabicColorName: 'Ø§Ø®Ø¶Ø± Ø²ÙŠØªÙˆÙ†ÙŠ ØºØ§Ù…Ù‚',
    color: '#556b2f',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Olive',
    arabicColorName: 'Ø²ÙŠØªÙˆÙ†ÙŠ',
    color: '#808000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Dark Green',
    arabicColorName: 'Ø§Ø®Ø¶Ø± ØºØ§Ù…Ù‚',
    color: '#006400',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Green',
    arabicColorName: 'Ø£Ø®Ø¶Ø±',
    color: '#008000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Sea Green',
    arabicColorName: 'Ø§Ø®Ø¶Ø± Ø¨Ø­Ø±ÙŠ',
    color: '#2e8b57',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Spring Green',
    arabicColorName: 'Ø§Ø®Ø¶Ø± Ø±Ø¨ÙŠØ¹ÙŠ',
    color: '#00ff7f',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Light Green',
    arabicColorName: 'Ø£Ø®Ø¶Ø± ÙØ§ØªØ­',
    color: '#90ee90',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Lime Green',
    arabicColorName: 'Ø§Ø®Ø¶Ø± Ù„ÙŠÙ…ÙˆÙ†ÙŠ',
    color: '#32cd32',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Lime',
    arabicColorName: 'Ù„ÙŠÙ…ÙˆÙ†ÙŠ',
    color: '#00ff00',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø®Ø¶Ø±Ø§Ø¡',
    colorName: 'Green Yellow',
    arabicColorName: 'Ø£ØµÙØ± Ù…Ø®Ø¶Ø±',
    color: '#adff2f',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Dark Slate Blue',
    arabicColorName: 'Ø§Ø²Ø±Ù‚ Ø´Ø§Ø­Ø¨ ØºØ§Ù…Ù‚',
    color: '#483d8b',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Indigo',
    arabicColorName: 'Ù†ÙŠÙ„ÙŠ',
    color: '#4b0082',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Purple',
    arabicColorName: 'Ø£Ø­Ù…Ø± Ø§Ø±Ø¬ÙˆØ§Ù†ÙŠ',
    color: '#800080',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Amethyst',
    arabicColorName: 'Ø§ÙˆØ±ÙƒÙŠØ¯ÙŠ ØºØ§Ù…Ù‚',
    color: '#9966cc',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Medium Orchid',
    arabicColorName: 'Ø§ÙˆØ±ÙƒÙŠØ¯ÙŠ Ù…Ø¹ØªØ¯Ù„',
    color: '#ba55d3',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Violet',
    arabicColorName: 'Ø§Ù„Ø¨Ù†ÙØ³Ø¬Ù‰',
    color: '#ee82ee',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Mauve',
    arabicColorName: 'Ø¨Ù†ÙØ³Ø¬ÙŠ ÙØ§ØªØ­',
    color: '#cc99ff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø£Ø±Ø¬ÙˆØ§Ù†ÙŠØ©',
    colorName: 'Lavender',
    arabicColorName: 'Ø§Ù„Ù„Ø§ÙÙ†Ø¯Ø±',
    color: '#e6e6fa',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„ØµÙØ±Ø§Ø¡',
    colorName: 'Dark Khaki',
    arabicColorName: 'ÙƒØ§ÙƒÙŠ ØºØ§Ù…Ù‚',
    color: '#bdb76b',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„ØµÙØ±Ø§Ø¡',
    colorName: 'Khaki',
    arabicColorName: 'ÙƒØ§ÙƒÙŠ',
    color: '#f0e68c',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„ØµÙØ±Ø§Ø¡',
    colorName: 'Light Yellow',
    arabicColorName: 'Ø£ØµÙØ± ÙØ§ØªØ­',
    color: '#ffffe0',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„ØµÙØ±Ø§Ø¡',
    colorName: 'Yellow',
    arabicColorName: 'Ø£ØµÙØ±',
    color: '#ffff00',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„ØµÙØ±Ø§Ø¡',
    colorName: 'Gold',
    arabicColorName: 'Ø°Ù‡Ø¨ÙŠ',
    color: '#ffd700',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Rust',
    arabicColorName: 'Ø±Ø³ØªÙŠ',
    color: '#bf360c',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Persimmon',
    arabicColorName: 'Ø¨Ø±Ø³ÙŠÙ…ÙˆÙ†',
    color: '#e65100',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Orange',
    arabicColorName: 'Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠ',
    color: '#ffa500',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Dark Orange',
    arabicColorName: 'Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠ ØºØ§Ù…Ù‚',
    color: '#ff8c00',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Orange Red',
    arabicColorName: 'Ø£Ø­Ù…Ø± Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠ',
    color: '#ff4500',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Tomato',
    arabicColorName: 'Ø·Ù…Ø§Ø·Ù…ÙŠ',
    color: '#ff6347',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Coral',
    arabicColorName: 'Ù…Ø±Ø¬Ø§Ù†ÙŠ',
    color: '#ff7f50',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¨Ø±ØªÙ‚Ø§Ù„ÙŠØ©',
    colorName: 'Light Salmon',
    arabicColorName: 'Ø³Ù„Ù…ÙˆÙ†ÙŠ ÙØ§ØªØ­',
    color: '#ffa07a',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Pale Violet Red',
    arabicColorName: 'Ø§Ø­Ù…Ø± Ø¨Ù†ÙØ³Ø¬ÙŠ Ø¨Ø§Ù‡Øª',
    color: '#db7093',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Medium Violet Red',
    arabicColorName: 'Ø§Ø­Ù…Ø± Ø¨Ù†ÙØ³Ø¬ÙŠ Ù…Ø¹ØªØ¯Ù„',
    color: '#c71585',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'fuchsia',
    arabicColorName: 'ÙÙˆØ´ÙŠØ§',
    color: '#ff00ff',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Cardinal',
    arabicColorName: 'ÙƒØ§Ø±Ø¯ÙŠÙ†Ø§Ù„',
    color: '#c2185b',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Ruby',
    arabicColorName: 'Ø±ÙˆØ¨ÙŠ',
    color: '#e91e63',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Dark Pink',
    arabicColorName: 'ÙˆØ±Ø¯ÙŠ ØºØ§Ù…Ù‚',
    color: '#f06292',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Deep Pink',
    arabicColorName: 'ÙˆØ±Ø¯ÙŠ Ø¹Ù…ÙŠÙ‚',
    color: '#ff1493',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Hot Pink',
    arabicColorName: 'ÙˆØ±Ø¯ÙŠ ØµØ§Ø±Ø®',
    color: '#ff69b4',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ù‚Ø±Ù†ÙÙ„ÙŠØ©',
    colorName: 'Pink',
    arabicColorName: 'ÙˆØ±Ø¯Ù‰',
    color: '#ffc0cb',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Dark Red',
    arabicColorName: 'Ø£Ø­Ù…Ø± ØºØ§Ù…Ù‚',
    color: '#8b0000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Fire Brick',
    arabicColorName: 'Ø·ÙˆØ¨ÙŠ',
    color: '#b22222',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Red',
    arabicColorName: 'Ø£Ø­Ù…Ø±',
    color: '#ff0000',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Light Salmon',
    arabicColorName: 'Ø³Ù„Ù…ÙˆÙ†ÙŠ ÙØ§ØªØ­',
    color: '#ffa07a',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Salmon',
    arabicColorName: 'Ø³Ù„Ù…ÙˆÙ†ÙŠ',
    color: '#fa8072',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Light Coral',
    arabicColorName: 'Ù…Ø±Ø¬Ø§Ù†ÙŠ ÙØ§ØªØ­',
    color: '#f08080',
  },
  {
    group: 'Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø­Ù…Ø±Ø§Ø¡',
    colorName: 'Indian Red',
    arabicColorName: 'Ø£Ø­Ù…Ø± Ù‡Ù†Ø¯ÙŠ',
    color: '#cd5c5c',
  },
];
