export const CMS_ADD_PRODUCT = 'CMS_ADD_PRODUCT';
export const CMS_INTERNAL_CATEGORIES = 'CMS_INTERNAL_CATEGORIES';
export const CMS_COMMERCIAL_CATEGORIES = 'CMS_COMMERCIAL_CATEGORIES';
export const CMS_ADD_EDIT_PRODUCT_COMMERCIAL_CATEGORIES = 'CMS_ADD_EDIT_PRODUCT_COMMERCIAL_CATEGORIES';
export const CMS_BUNDLES = 'CMS_BUNDLES';