export const COLOR_VARIANTS = [
  {
    group: "الألوان الرمادية",
    colorName: "Black",
    arabicColorName: "أسود",
    color: "#000000",
  },
  {
    group: "الألوان الرمادية",
    colorName: "Dark Slate Grey",
    arabicColorName: "رمادي شاحب غامق",
    color: "#2f4f4f",
  },
  {
    group: "الألوان الرمادية",
    colorName: "Grey",
    arabicColorName: "رمادي",
    color: "#808080",
  },
  {
    group: "الألوان الرمادية",
    colorName: "Dark Gray",
    arabicColorName: "رمادي غامق",
    color: "#a9a9a9",
  },
  {
    group: "الألوان الرمادية",
    colorName: "Light Grey",
    arabicColorName: "رمادي فاتح",
    color: "#d3d3d3",
  },
  {
    group: "الألوان الرمادية",
    colorName: "Silver",
    arabicColorName: "فضي",
    color: "#c0c0c0",
  },
  {
    group: "الألوان البيضاء",
    colorName: "White",
    arabicColorName: "أبيض",
    color: "#ffffff",
  },
  {
    group: "الألوان البيضاء",
    colorName: "Light Cyan",
    arabicColorName: "ازرق سماوي فاتح",
    color: "#e0ffff",
  },
  {
    group: "الألوان البيضاء",
    colorName: "Beige",
    arabicColorName: "البيج",
    color: "#f5f5dc",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Maroon",
    arabicColorName: "ماروني",
    color: "#800000",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Sienna",
    arabicColorName: "سيينا",
    color: "#a0522d",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Brown",
    arabicColorName: "بني",
    color: "#8b4513",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Chocolate",
    arabicColorName: "شيكولاتة",
    color: "#d2691e",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Sandy Brown",
    arabicColorName: "بني رملي",
    color: "#f4a460",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Bronze",
    arabicColorName: "نحاسي",
    color: "#dca270",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Burly Wood",
    arabicColorName: "خشبي",
    color: "#deb887",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Kashmir",
    arabicColorName: "كشمير",
    color: "#ccae94",
  },
  {
    group: "الألوان السمراء (البني)",
    colorName: "Creamy",
    arabicColorName: "كريمي",
    color: "#fffdd0",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Prussian Blue",
    arabicColorName: "كحلي غامق",
    color: "#000033",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Navy",
    arabicColorName: "كحلي",
    color: "#000066",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Darkblue",
    arabicColorName: "أزرق غامق",
    color: "#00008b",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Blue",
    arabicColorName: "أزرق",
    color: "#0000ff",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Medium Slate Blue",
    arabicColorName: "أزرق رمادي متوسط",
    color: "#7b68ee",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Dodger Blue",
    arabicColorName: "أزرق مراوغ",
    color: "#1e90ff",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Deep Sky Blue",
    arabicColorName: "ازرق سماوي عميق",
    color: "#00bfff",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Sky Blue",
    arabicColorName: "ازرق سماوي",
    color: "#87ceeb",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Steel Blue",
    arabicColorName: "ازرق رمادي",
    color: "#4682b4",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Cadet Blue",
    arabicColorName: "ازرق كاديت",
    color: "#5f9ea0",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Turquoise",
    arabicColorName: "فيروزي",
    color: "#40e0d0",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Pale Turquoise",
    arabicColorName: "تركواز شاحب",
    color: "#afeeee",
  },
  {
    group: "الألوان الزرقاء",
    colorName: "Aqua",
    arabicColorName: "سماوي",
    color: "#00ffff",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Dark Cyan",
    arabicColorName: "سماوي غامق",
    color: "#008b8b",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Dark Olive Green",
    arabicColorName: "اخضر زيتوني غامق",
    color: "#556b2f",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Olive",
    arabicColorName: "زيتوني",
    color: "#808000",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Dark Green",
    arabicColorName: "اخضر غامق",
    color: "#006400",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Green",
    arabicColorName: "أخضر",
    color: "#008000",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Sea Green",
    arabicColorName: "اخضر بحري",
    color: "#2e8b57",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Spring Green",
    arabicColorName: "اخضر ربيعي",
    color: "#00ff7f",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Light Green",
    arabicColorName: "أخضر فاتح",
    color: "#90ee90",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Lime Green",
    arabicColorName: "اخضر ليموني",
    color: "#32cd32",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Lime",
    arabicColorName: "ليموني",
    color: "#00ff00",
  },
  {
    group: "الألوان الخضراء",
    colorName: "Green Yellow",
    arabicColorName: "أصفر مخضر",
    color: "#adff2f",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Dark Slate Blue",
    arabicColorName: "ازرق شاحب غامق",
    color: "#483d8b",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Indigo",
    arabicColorName: "نيلي",
    color: "#4b0082",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Purple",
    arabicColorName: "أحمر ارجواني",
    color: "#800080",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Amethyst",
    arabicColorName: "اوركيدي غامق",
    color: "#9966cc",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Medium Orchid",
    arabicColorName: "اوركيدي معتدل",
    color: "#ba55d3",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Violet",
    arabicColorName: "البنفسجى",
    color: "#ee82ee",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Mauve",
    arabicColorName: "بنفسجي فاتح",
    color: "#cc99ff",
  },
  {
    group: "الألوان الأرجوانية",
    colorName: "Lavender",
    arabicColorName: "اللافندر",
    color: "#e6e6fa",
  },
  {
    group: "الألوان الصفراء",
    colorName: "Dark Khaki",
    arabicColorName: "كاكي غامق",
    color: "#bdb76b",
  },
  {
    group: "الألوان الصفراء",
    colorName: "Khaki",
    arabicColorName: "كاكي",
    color: "#f0e68c",
  },
  {
    group: "الألوان الصفراء",
    colorName: "Light Yellow",
    arabicColorName: "أصفر فاتح",
    color: "#ffffe0",
  },
  {
    group: "الألوان الصفراء",
    colorName: "Yellow",
    arabicColorName: "أصفر",
    color: "#ffff00",
  },
  {
    group: "الألوان الصفراء",
    colorName: "Gold",
    arabicColorName: "ذهبي",
    color: "#ffd700",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Rust",
    arabicColorName: "رستي",
    color: "#bf360c",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Persimmon",
    arabicColorName: "برسيمون",
    color: "#e65100",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Orange",
    arabicColorName: "برتقالي",
    color: "#ffa500",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Dark Orange",
    arabicColorName: "برتقالي غامق",
    color: "#ff8c00",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Orange Red",
    arabicColorName: "أحمر برتقالي",
    color: "#ff4500",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Tomato",
    arabicColorName: "طماطمي",
    color: "#ff6347",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Coral",
    arabicColorName: "مرجاني",
    color: "#ff7f50",
  },
  {
    group: "الألوان البرتقالية",
    colorName: "Light Salmon",
    arabicColorName: "سلموني فاتح",
    color: "#ffa07a",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Pale Violet Red",
    arabicColorName: "احمر بنفسجي باهت",
    color: "#db7093",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Medium Violet Red",
    arabicColorName: "احمر بنفسجي معتدل",
    color: "#c71585",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "fuchsia",
    arabicColorName: "فوشيا",
    color: "#ff00ff",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Cardinal",
    arabicColorName: "كاردينال",
    color: "#c2185b",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Ruby",
    arabicColorName: "روبي",
    color: "#e91e63",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Dark Pink",
    arabicColorName: "وردي غامق",
    color: "#f06292",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Deep Pink",
    arabicColorName: "وردي عميق",
    color: "#ff1493",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Hot Pink",
    arabicColorName: "وردي صارخ",
    color: "#ff69b4",
  },
  {
    group: "الألوان القرنفلية",
    colorName: "Pink",
    arabicColorName: "وردى",
    color: "#ffc0cb",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Dark Red",
    arabicColorName: "أحمر غامق",
    color: "#8b0000",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Fire Brick",
    arabicColorName: "طوبي",
    color: "#b22222",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Red",
    arabicColorName: "أحمر",
    color: "#ff0000",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Light Salmon",
    arabicColorName: "سلموني فاتح",
    color: "#ffa07a",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Salmon",
    arabicColorName: "سلموني",
    color: "#fa8072",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Light Coral",
    arabicColorName: "مرجاني فاتح",
    color: "#f08080",
  },
  {
    group: "الألوان الحمراء",
    colorName: "Indian Red",
    arabicColorName: "أحمر هندي",
    color: "#cd5c5c",
  },
];
